"""Compose card grids from SVG dimensions, without README pixel sizes."""

import hashlib
from html import escape
import re
import xml.etree.ElementTree as ET

SVG = '{http://www.w3.org/2000/svg}'
STEMS = ('github-stats', 'top-languages', 'streak', 'productive-time-animated-v2')


def scope_css(css, scope):
    """Scope selectors while preserving keyframes and nested media rules."""
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    result = []
    cursor = 0
    while cursor < len(css):
        opening = css.find('{', cursor)
        if opening < 0:
            result.append(css[cursor:])
            break
        prelude = css[cursor:opening].strip()
        depth, closing = 1, opening + 1
        while depth and closing < len(css):
            depth += (css[closing] == '{') - (css[closing] == '}')
            closing += 1
        if depth:
            raise ValueError('Unbalanced card stylesheet')
        body = css[opening + 1:closing - 1]
        if prelude.startswith('@media') or prelude.startswith('@supports'):
            body = scope_css(body, scope)
        elif not prelude.startswith('@'):
            prelude = ', '.join(scope + ' ' + selector.strip() for selector in prelude.split(','))
        result.append(prelude + '{' + body + '}')
        cursor = closing
    return '\n'.join(result)


def scoped_card(data, prefix):
    source = data.decode('utf-8')
    for name in set(re.findall(r'@keyframes\s+([\w-]+)', source)):
        source = re.sub(r'(?<![\w-])' + re.escape(name) + r'(?![\w-])', prefix + '-' + name, source)
    data = source.encode('utf-8')
    root = ET.fromstring(data)
    replacements = {e.get('id'): prefix + '-' + e.get('id') for e in root.iter() if e.get('id')}
    for element in root.iter():
        if element.get('id'):
            element.set('id', replacements[element.get('id')])
        for key, value in list(element.attrib.items()):
            if key != 'id':
                for old, new in replacements.items():
                    value = value.replace('#' + old, '#' + new)
                element.set(key, value)
        if element.tag == SVG + 'style':
            css = element.text or ''
            for old, new in replacements.items():
                css = css.replace('#' + old, '#' + new)
            element.text = scope_css(css, '#' + prefix)
    root.set('id', prefix)
    return root


def compose(cards, columns):
    """Size columns/rows from source images; isolate each card's SVG styles."""
    sizes = []
    for data in cards:
        root = ET.fromstring(data)
        sizes.append(tuple(float(root.get(key).removesuffix('px')) for key in ('width', 'height')))
    widths = [max(width for index, (width, _) in enumerate(sizes) if index % columns == col)
              for col in range(columns)]
    rows = (len(cards) + columns - 1) // columns
    heights = [max(height for index, (_, height) in enumerate(sizes) if index // columns == row)
               for row in range(rows)]
    if columns == 1:
        heights = [height * widths[0] / width for width, height in sizes]
    gap = min(heights) * 0.03
    width = sum(widths) + gap * (columns - 1)
    height = sum(heights) + gap * (rows - 1)
    root = ET.Element(SVG + 'svg', {'width': f'{width:g}', 'height': f'{height:g}',
                                  'viewBox': f'0 0 {width:g} {height:g}', 'role': 'img'})
    ET.SubElement(root, SVG + 'title').text = 'GitHub statistics, languages, contribution streak and commit times'
    for index, data in enumerate(cards):
        col, row = index % columns, index // columns
        child = scoped_card(data, f'card-{index}')
        x, y = sum(widths[:col]) + col * gap, sum(heights[:row]) + row * gap
        cell = ET.SubElement(root, SVG + 'g', {
            'id': f'cell-{index}',
            'transform': f'translate({x:g} {y:g}) scale({widths[col] / sizes[index][0]:g} {heights[row] / sizes[index][1]:g})',
        })
        cell.append(child)
    ET.register_namespace('', SVG[1:-1])
    return ET.tostring(root, encoding='utf-8')


def publish_layout(root):
    directory = root / 'assets/readme-cards'
    cards = [(directory / (stem + '.svg')).read_bytes() for stem in STEMS]
    paths = {}
    for variant, columns in (('wide', 2), ('narrow', 1)):
        data = compose(cards, columns)
        name = f'overview-{variant}-{hashlib.sha256(data).hexdigest()[:16]}.svg'
        (directory / name).write_bytes(data)
        paths[variant] = 'assets/readme-cards/' + name
        # Keep immutable versions: a cached README may still reference an old URL.
    title = ET.fromstring(cards[2]).find(SVG + 'title')
    tooltip = escape(title.text if title is not None else 'GitHub profile statistics', quote=True)
    # A picture element supports mobile stacking in GitHub's sanitized README.
    # The breakpoint follows the natural wide layout width rather than card-specific pixels.
    breakpoint = ET.fromstring(compose(cards, 2)).get('width')
    content = f'''<!-- Generated by scripts/card_layout.py; card dimensions come from the source SVGs. -->
<picture>
  <source media="(max-width: {breakpoint}px)" srcset="{paths['narrow']}" />
  <img alt="GitHub profile statistics" title="{tooltip}" src="{paths['wide']}" />
</picture>
'''
    (root / 'README.md').write_text(content, encoding='utf-8', newline='\n')
