"""Compose card grids from SVG dimensions, without README pixel sizes."""

import base64
import hashlib
from html import escape
import re
import xml.etree.ElementTree as ET

SVG = '{http://www.w3.org/2000/svg}'
STEMS = ('github-stats', 'top-languages', 'streak', 'productive-time-animated-v2')


def compose(cards, columns):
    """Size columns/rows from source images; isolate each card's SVG styles."""
    sizes = []
    for data in cards:
        root = ET.fromstring(data)
        sizes.append(tuple(float(root.get(key).removesuffix('px')) for key in ('width', 'height')))
    widths = [max(width for index, (width, _) in enumerate(sizes) if index % columns == col)
              for col in range(columns)]
    rows = (len(cards) + columns - 1) // columns
    heights = [max(height for index, (_, height) in enumerate(sizes) if index // columns == row)
               for row in range(rows)]
    gap = min(heights) * 0.03
    width = sum(widths) + gap * (columns - 1)
    height = sum(heights) + gap * (rows - 1)
    root = ET.Element(SVG + 'svg', {'width': f'{width:g}', 'height': f'{height:g}',
                                  'viewBox': f'0 0 {width:g} {height:g}', 'role': 'img'})
    ET.SubElement(root, SVG + 'title').text = 'GitHub statistics, languages, contribution streak and commit times'
    for index, data in enumerate(cards):
        col, row = index % columns, index // columns
        ET.SubElement(root, SVG + 'image', {
            'x': f'{sum(widths[:col]) + col * gap:g}',
            'y': f'{sum(heights[:row]) + row * gap:g}',
            'width': f'{widths[col]:g}', 'height': f'{heights[row]:g}',
            'preserveAspectRatio': 'none',
            'href': 'data:image/svg+xml;base64,' + base64.b64encode(data).decode(),
        })
    ET.register_namespace('', SVG[1:-1])
    return ET.tostring(root, encoding='utf-8')


def publish_layout(root):
    directory = root / 'assets/readme-cards'
    cards = [(directory / (stem + '.svg')).read_bytes() for stem in STEMS]
    paths = {}
    for variant, columns in (('wide', 2), ('narrow', 1)):
        data = compose(cards, columns)
        name = f'overview-{variant}-{hashlib.sha256(data).hexdigest()[:16]}.svg'
        (directory / name).write_bytes(data)
        paths[variant] = 'assets/readme-cards/' + name
        for old in directory.glob(f'overview-{variant}-*.svg'):
            if re.fullmatch(r'overview-' + variant + r'-[0-9a-f]{16}\.svg', old.name) and old.name != name:
                old.unlink()
    title = ET.fromstring(cards[2]).find(SVG + 'title')
    tooltip = escape(title.text if title is not None else 'GitHub profile statistics', quote=True)
    # A picture element supports mobile stacking in GitHub's sanitized README.
    # The breakpoint follows the natural wide layout width rather than card-specific pixels.
    breakpoint = ET.fromstring(compose(cards, 2)).get('width')
    content = f'''<!-- Generated by scripts/card_layout.py; card dimensions come from the source SVGs. -->
<picture>
  <source media="(max-width: {breakpoint}px)" srcset="{paths['narrow']}" />
  <img alt="GitHub profile statistics" title="{tooltip}" src="{paths['wide']}" />
</picture>
'''
    (root / 'README.md').write_text(content, encoding='utf-8', newline='\n')
